name: omitrans
channels:
- pytorch
- defaults
dependencies:
- python=3.8.10
- pip=21.1.1
- pytorch=1.8.1
- scikit-learn=1.0.2
- pandas=1.3.5
- pip:
  - tensorboard==2.5.0
  - prefetch_generator==1.0.1
  - tables==3.6.1
